# Lobby List

<LobbyList>:
    id: 'lobby_list'
    lobby_list_filter: 'lobby_list_filter'
    list_of_lobbies: 'list_of_lobbies'

    # layout goes here
    Filter:
        id: 'lobby_list_filter'
    ListOfLobbies
        id: 'list_of_lobbies'

<Filter>:
    id: 'lobby_list_filter'

<ListOfLobbies>:
    id: 'list_of_lobbies'

<LobbyInfo>:
    id: 'lobby_info'

    Text:
        id: 'lobby_name'
    # ListOfRoles:
    #    id: 'list_of_roles'
    Button:
        id: 'join_lobby'