# Main menu kivy stuff

<MainMenu>:
    id: 'main_menu'
    create_lobby: 'create_lobby'
    join_lobby: 'join_lobby'
    stats: 'stats'
    settings: 'settings'
    customize_character: 'customize_character'

    # Should have some sort of layout, but need to research that
    Button:
        id: 'create_lobby'
    Button:
        id: 'join_lobby'
    Button:
        id: 'stats'
    Button:
        id: 'settings'
    Button:
        id: 'customize_character'